# Generated by Django 5.0.1 on 2024-02-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_aboutme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_date',
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]